name: EconomyShop
version: 1.0.0
api: 5.0.0
main: EconomyShop\Main
description: Hệ thống shop kinh tế dạng rương cho MCPE 1.21
author: Phat bel
website: https://github.com/huynhletanphat
commands:
  shop:
    description: Mở cửa hàng
    permission: economyshop.use
permissions:
  economyshop.use:
    default: true
  economyshop.admin:
    default: op
